#!/usr/bin/env python3
"""design/face_params.json -> include/face_params.h

Run from firmware-face/:  python tools/gen_params.py
The Face Lab page uses the same JSON, so a face tuned there looks the same on
the board. Parameter order must match NUM in design/face_engine.js.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
NUM = ['eyeW', 'eyeH', 'radius', 'gap', 'dy', 'lid', 'slant', 'asym', 'lower',
       'mouthW', 'curve', 'open', 'mouthDx', 'gazeX', 'gazeY']
RINGS = ['off', 'pulse', 'flash', 'spin']
LAYOUT = ['cx', 'eyeY', 'mouthY', 'ringR', 'ringW', 'talkOpenH', 'mouthThick',
          'gazeMaxX', 'gazeMaxY', 'morphMs', 'colorMs', 'brightAwake', 'brightAsleep']


def snake(name):
    return ''.join('_' + ch if ch.isupper() else ch for ch in name).upper()


def main():
    params = json.loads((ROOT / 'design' / 'face_params.json').read_text())
    lay, emos = params['layout'], params['emotions']
    out = ['// GENERATED by tools/gen_params.py from design/face_params.json - do not edit.',
           '#pragma once', '#include <stdint.h>', '']
    for k in LAYOUT:
        out.append(f'#define LAYOUT_{snake(k)} {lay[k]}')
    out.append('')
    out.append('enum ParamIndex { ' + ', '.join('P_' + snake(k) for k in NUM) + ' };')
    out.append(f'static const int kNumParams = {len(NUM)};')
    out.append('enum RingMode { ' + ', '.join('RING_' + r.upper() for r in RINGS) + ' };')
    out.append('')
    out.append('struct EmotionDef { const char* name; float p[kNumParams]; uint8_t rgb[3]; uint8_t ring; };')
    out.append('static const EmotionDef kEmotions[] = {')
    for name, e in emos.items():
        vals = ', '.join(f'{float(e[k])!r}f' for k in NUM)
        h = e['color'].lstrip('#')
        rgb = ', '.join(str(int(h[i:i + 2], 16)) for i in (0, 2, 4))
        out.append(f'  {{"{name}", {{{vals}}}, {{{rgb}}}, RING_{e["ring"].upper()}}},')
    out.append('};')
    out.append(f'static const int kNumEmotions = {len(emos)};')
    (ROOT / 'include' / 'face_params.h').write_text('\n'.join(out) + '\n')
    print(f'wrote include/face_params.h ({len(emos)} emotions)')


if __name__ == '__main__':
    main()
