#!/usr/bin/env python3
"""Make include/lv_conf.h from LVGL 8.4's lv_conf_template.h.

Usage: python tools/make_lv_conf.py <path-to-lvgl>/lv_conf_template.h
Only needed if include/lv_conf.h is lost; the settings are listed below.
"""
import pathlib
import re
import sys

SET = {
    'LV_COLOR_DEPTH': '16',
    'LV_COLOR_16_SWAP': '0',          # Arduino_GFX's draw16bitRGBBitmap swaps itself
    'LV_MEM_CUSTOM': '0',
    'LV_MEM_SIZE': '(64U * 1024U)',   # internal RAM; the draw masks live here
    'LV_DISP_DEF_REFR_PERIOD': '16',
    'LV_INDEV_DEF_READ_PERIOD': '30',
    'LV_TICK_CUSTOM': '1',
    'LV_USE_PERF_MONITOR': '0',
    'LV_USE_MEM_MONITOR': '0',
    'LV_USE_LOG': '0',
    'LV_FONT_MONTSERRAT_14': '1',
    'LV_FONT_MONTSERRAT_28': '1',
    'LV_FONT_MONTSERRAT_48': '1',
    'LV_USE_DEMO_WIDGETS': '0',
}

src = pathlib.Path(sys.argv[1]).read_text()
src = src.replace('#if 0 /*Set it to "1" to enable content*/', '#if 1 /*Set it to "1" to enable content*/', 1)
for key, val in SET.items():
    src, n = re.subn(rf'^(\s*#define {key}\s+)\S.*?(\s*(/\*.*)?)$', rf'\g<1>{val}\2', src, count=1, flags=re.M)
    if not n:
        sys.exit(f'{key} not found in template')
out = pathlib.Path(__file__).resolve().parent.parent / 'include' / 'lv_conf.h'
out.write_text('/* Generated by tools/make_lv_conf.py from LVGL 8.4 lv_conf_template.h */\n' + src)
print('wrote', out)
