// GENERATED by tools/gen_params.py from design/face_params.json - do not edit.
#pragma once
#include <stdint.h>

#define LAYOUT_CX 233
#define LAYOUT_EYE_Y 200
#define LAYOUT_MOUTH_Y 334
#define LAYOUT_RING_R 222
#define LAYOUT_RING_W 7
#define LAYOUT_TALK_OPEN_H 58
#define LAYOUT_MOUTH_THICK 11
#define LAYOUT_GAZE_MAX_X 20
#define LAYOUT_GAZE_MAX_Y 13
#define LAYOUT_MORPH_MS 90
#define LAYOUT_COLOR_MS 220
#define LAYOUT_BRIGHT_AWAKE 190
#define LAYOUT_BRIGHT_ASLEEP 45

enum ParamIndex { P_EYE_W, P_EYE_H, P_RADIUS, P_GAP, P_DY, P_LID, P_SLANT, P_ASYM, P_LOWER, P_MOUTH_W, P_CURVE, P_OPEN, P_MOUTH_DX, P_GAZE_X, P_GAZE_Y };
static const int kNumParams = 15;
enum RingMode { RING_OFF, RING_PULSE, RING_FLASH, RING_SPIN };

struct EmotionDef { const char* name; float p[kNumParams]; uint8_t rgb[3]; uint8_t ring; };
static const EmotionDef kEmotions[] = {
  {"neutral", {108.0f, 150.0f, 50.0f, 88.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 72.0f, 8.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {69, 227, 210}, RING_OFF},
  {"happy", {118.0f, 132.0f, 58.0f, 90.0f, -4.0f, 0.0f, 0.0f, 0.0f, 0.42f, 112.0f, 30.0f, 0.18f, 0.0f, 0.0f, -4.0f}, {255, 197, 77}, RING_PULSE},
  {"sad", {102.0f, 132.0f, 46.0f, 84.0f, 14.0f, 0.14f, -26.0f, 0.0f, 0.0f, 84.0f, -22.0f, 0.0f, 0.0f, 0.0f, 8.0f}, {94, 139, 255}, RING_OFF},
  {"angry", {114.0f, 122.0f, 34.0f, 86.0f, 6.0f, 0.22f, 30.0f, 0.0f, 0.0f, 80.0f, -12.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {255, 90, 74}, RING_OFF},
  {"surprised", {124.0f, 172.0f, 62.0f, 92.0f, -8.0f, 0.0f, 0.0f, 0.0f, 0.0f, 46.0f, 0.0f, 0.85f, 0.0f, 0.0f, -6.0f}, {230, 252, 255}, RING_FLASH},
  {"sleepy", {112.0f, 146.0f, 50.0f, 88.0f, 8.0f, 0.6f, -8.0f, 0.0f, 0.0f, 52.0f, 2.0f, 0.0f, 0.0f, 0.0f, 6.0f}, {127, 166, 201}, RING_OFF},
  {"thinking", {104.0f, 140.0f, 46.0f, 86.0f, -2.0f, 0.16f, 8.0f, 0.14f, 0.0f, 50.0f, -4.0f, 0.0f, 28.0f, 16.0f, -11.0f}, {178, 140, 255}, RING_SPIN},
};
static const int kNumEmotions = 7;
